name: Build and Deploy to ACR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: tuncicd2026.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image
      run: |
        docker build . -t tuncicd2026.azurecr.io/hello-flask:latest
        docker push tuncicd2026.azurecr.io/hello-flask:latest